version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      restart: always
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: ceresdb
    ports:
      - 3308:3306
    volumes:
      - datavolume:/var/lib/mysql

  backend:
    image: node:alpine
    volumes:
      - .:/usr/app/
    depends_on:
      - db
    working_dir: /usr/app
    ports:
      - 8080:8080
    command: npm run dev
volumes:
  datavolume: